import { FC, useState } from 'react';
import { Box } from '@mui/system';
import { Container } from '@mui/material';
import { documentation } from './api';
import ApiDocumentationMenu from './ApiDocumentationMenu';
import ApiDocumentationEndpoint from './ApiDocumentationEndpoint';
import ApiDocumentationOverview from './ApiDocumentationOverview';
import Logo from './Logo';

interface RestApiDocumentationAppProps {
  endpoints: documentation;
}

const ApiDocumentationApp: FC<RestApiDocumentationAppProps> = ({ endpoints }) => {
  const [activeEndpoint, setEndpoint] = useState<string>();
  const [menuOpen, setMenuOpen] = useState(true);
  const selectedEndpoint = endpoints.find((endpointItem) => endpointItem.class === activeEndpoint);

  return (
    <Box sx={{ margin: '3em 0' }}>
      <Container>
        <Box sx={{ display: 'flex' }}>
          <Box sx={{ width: menuOpen ? '20%' : '8%' }}>
            <ApiDocumentationMenu
              endpoints={endpoints}
              activeEndpoint={activeEndpoint}
              isMenuOpen={menuOpen}
              setEndpoint={setEndpoint}
              setMenuOpen={() => setMenuOpen(!menuOpen)}
            />
          </Box>
          <Box sx={{ padding: '0 1.5em' }}>
            {selectedEndpoint ? (
              <ApiDocumentationEndpoint endpoint={selectedEndpoint} />
            ) : (
              <ApiDocumentationOverview endpoints={endpoints} setEndpoint={setEndpoint} />
            )}
          </Box>
        </Box>
        <Box
          sx={{
            textAlign: 'center',
            margin: '1em',
            marginTop: '2em',
            paddingTop: '1em',
            borderTop: '1px solid #ccc',
          }}
        >
          <Logo height={20} />
          <Box sx={{ fontSize: '10pt', marginTop: '1em' }}>
            Generated by&nbsp;
            <a href="https://github.com/baraja-core/structured-api-doc" target="_blank" rel="noreferrer">
              BRJ documentation
            </a>
            .
          </Box>
        </Box>
      </Container>
    </Box>
  );
};

export default ApiDocumentationApp;
